### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by ultrono** [f9webltd/laravel-api-response-helpers#1]
Currently the tests are fairly repetitive, it would be good to reduce duplication.

**Comment by rkhan06** [comment]
hi @ultrono, i would love to work on this . I have not contributed to any project yet so can you guide me a little on what needs to be done ?

**Comment by ultrono** [comment]
Thanks for the interest!

The repetition in the tests bugs me to be honest and some refactoring would be appreciated 🪐 

You basically create something called a pull request. There's a good video on YouTube that explains this - https://www.youtube.com/watch?v=rgbCcBNZcdQ.
