### ISSUE TITLE
Test additional objects types

### ISSUE THREAD

**Issue by ultrono** [f9webltd/laravel-api-response-helpers#11]
As the package now supports content types other than arrays, it would be good to test common use cases.

The tests currently cover array and Laravel collection types.

Ideally having tests covering Eloquent collections and API resources would be good.

This will also require updating workflows.

I'd imagine we'd end up with something similar to https://github.com/f9webltd/laravel-deletable/tree/master/tests.

**Comment by kzvonov** [comment]
@ultrono Hey Hi 👋 

I'm new to open source, but I would like to take this issue)
A little about me, I have around 5 years of development experience & 3 years with Laravel.

**Comment by ultrono** [comment]
@kzvonov sounds good, look forwards to your PR 👍

**Comment by kzvonov** [comment]
@ultrono Don't you mind if I'll add Docker for local development?
I get used to keeping everything in Docker 😅

**Comment by ultrono** [comment]
How you work locally is entirely your own choice :)

**Comment by kzvonov** [comment]
@ultrono, I've created the PR) Let me know if there are any problems.

**Comment by kzvonov** [comment]
@ultrono the PR has been merged) I think we can close this one.
