### ISSUE TITLE
Pagination Response 

### ISSUE THREAD

**Issue by AhemdHegazy** [f9webltd/laravel-api-response-helpers#14]
Hi There This is a good work and a very useful package but wee need a response function for pagination 
```
  public function returnDataPagination($paginator,contents,$page)
    {
        if($paginator->url($page))
        {
           $contents = $this->morphToArray($contents);

          $data = [] === $contents
              ? ['success' => true]
              : $contents;
            return $this->apiResponse($data);
        }
    }
```

this is the function I hope this help
thanks

**Comment by ultrono** [comment]
Thanks for the contribution @AhemdHegazy. Can you provide a PR with tests?

**Comment by ultrono** [comment]
Quickly looking at the example code:

- rename the method to `respondWithPagination` 
- it would be better to type hint the `$paginator` argument
- unsure of the if statement is required, either way I much prefer early returns

If anything, a helper / alias method may be easier as Laravels paginator implement `Arrayable` (https://github.com/illuminate/pagination/blob/master/Paginator.php#L141-L154), which the package now handles.

So in theory we could have a simple convenience method:

```php
public function respondWithPagination(\Illuminate\Pagination\Paginator $paginator): JSonResponse
{
   return $this->respondWithSuccess($paginator);
}
```

However, you can currently do:

```php
$this->respondWithSuccess(\Illuminate\Pagination\Paginator $paginator);
```

Again open to opinions here :smile:

**Comment by ultrono** [comment]
Apart from an additional utility method `respondWithPagination` I'm unsure of this is needed, as the package handles multiple common Laravel interfaces, see https://github.com/f9webltd/laravel-api-response-helpers/tree/1.5.0#use-with-additional-object-types. 

At most I'd be open to a PR with tests, for the mentioned convenience method. Opinions?

**Comment by AhemdHegazy** [comment]
thanks

**Comment by ultrono** [comment]
@AhemdHegazy Were you going to handle this via a PR?
