### ISSUE TITLE
Advanced use case: respondFailedValidation

### ISSUE THREAD

**Issue by valentinhttr** [f9webltd/laravel-api-response-helpers#20]
Hi,

The `respondFailedValidation` method simply returns a message and the response looks like this if multiple errors are present:

```json
{
    "message": "The test field is required. (and 1 more error)"
}
```

Wouldn't it be better if we could know on which field the error occurs? (and have the error code so we can do the translation outside the API maybe).

Example:
```json
{
    "message": "validation_rule_failed",
    "errors": {
        "myField.required": {
            "code": "validation_rule_required",
            "field": "myField",
            "message": "The test field is required."
        }
    }
}
```

What do you think about this?

Thank you.

**Comment by ultrono** [comment]
Thanks for the suggestion! 

To add a bit of backup this package was developed to mainly solve my own problems. I typically use form requests for validation and so all validation errors are returned automatically by Laravel. The `respondFailedValidation` method was therefore for me to return some additional ADHOC error message within a controller.

I'd definitely be open to a PR to enhance this method if you're not validating using form requests or using the `$request->validate()` method. I'd be keen to keep the same API so we can make this a none breaking change.

Maybe an API something along the lines of:

`respondFailedValidation(?string $message = null, ?array $errors = [])`

So `respondFailedValidation()` would return a generic message, built into the package, `respondFailedValidation('Ouch')` would return a response without an errors and just a message. Finally, `respondFailedValidation('Ouch', $errors)` would return the structure suggested by yourself.

What do you think?

**Comment by valentinhttr** [comment]
Oh well @ultrono, I must have missed an episode then. So, If I use a form request and send an `application/json` header, laravel should return all errors as a json response? Is that what you mean?

**Comment by ultrono** [comment]
@valh1996 There will be valid use cases to return validation errors from within the controller, but if use Laravel form requests errors (along with the correct statu8s code) are returned for you. See https://laravel.com/docs/9.x/validation#form-request-validation
