### ISSUE TITLE
Response File Type

### ISSUE THREAD

**Issue by gogl92** [f9webltd/laravel-api-response-helpers#21]
As a developer sometimes I'd like to respond with a file in certain routes, e.g.

Instead of constructing a response like:

```
    /**
     * Returns the file as a response.
     *
     * @return Response
     */
    public function getInvoiceAsPdf(): Response
    {
        $file = Storage::disk($this->disk)->file('invoice.pdf');

        return new Response($file, Response::HTTP_OK, [
            'Content-Type'        => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="invoice.pdf"',
            'Content-Length'      => strlen($file),
        ]);
    }
```

I can simply do

```
    /**
     * Returns the file as a response.
     *
     * @return Response
     */
    public function getInvoiceAsPdf(): Response
    {
        $file = Storage::disk($this->disk)->file('invoice.pdf');

        $this->respondWitFile($file);
    }
```

**Comment by ultrono** [comment]
Thanks for the suggestion!

This package is focused towards API responses, typically where the return type from your method is `Illuminate\Http\JsonResponse`.

I therefore think returning a HTTP response isn't applicable. Your suggestion would however be adjusted to return information about a file in Json format. 

However, I may be incorrect here and returning a full file response from an API may be valid - I just haven't seen that before :) 

Would be open to a PR either way.

**Comment by ultrono** [comment]
Closing as no reply :/

**Comment by gogl92** [comment]
@ultrono sorry for the late reply, I'd like to work in a PR proposal to add this functionality, I'll try you in the PR when ready for review.

**Comment by ultrono** [comment]
Sorry for the delay, Looking forwards to the PR! :+1:
