### ISSUE TITLE
Pagination in respondWithSuccess

### ISSUE THREAD

**Issue by erloncharlesbf** [f9webltd/laravel-api-response-helpers#31]
It would be interesting to have the model's pagination information in respondWithSuccess

```json
{
  "meta": {
    "page": {
      "current-page": 2,
      "per-page": 15,
      "from": 16,
      "to": 30,
      "total": 50,
      "last-page": 4
    }
  },
  "items": [...]
}
```

**Comment by ultrono** [comment]
Hi,

Pretty sure this should work already, as Laravel's pagination response implements `ArrayAccess`.

What is the output of:

```php
$users = User::query()->paginate();

return $this->respondWithSuccess($users);
```

**Comment by Hesesses** [comment]
Hello,

Thank you for creating this package, it works perfectly when returning single items, but when returning an array with pagination, there is a probem.

I have this code:

```
$events = Event::paginate(20);
$data = new EventCollection($events);
return $this->respondWithSuccess($data);
```
This only returns data array with event data, so everything related to pagination is gone.

Would be nice to keep the pagination data. Now we need to return data without respondWithSuccess:
```
$events = Event::paginate(20);
return  new EventCollection($events);
```

**Comment by ultrono** [comment]
Hi,

I'll have a play with and get back to you. As I don't have access to your `EventCollection` class, I'll experiment using a normal paginated Eloquent Collection first.

However, very open to PRs on this 🔥 

Cheers

**Comment by Hesesses** [comment]
Sorry for late reply. My EventCollection is Laravel api resource collection: https://laravel.com/docs/11.x/eloquent-resources#resource-collections

**Comment by plamenradev** [comment]
Is there a solution to the problem with paginated results and returning the pagination meta data when using API resources?
