### ISSUE TITLE
Content for respondNoContent?

### ISSUE THREAD

**Issue by berbeflo** [f9webltd/laravel-api-response-helpers#5]
I'm a bit confused about the method `respondNoContent`.
The current signature is: `public function respondNoContent(?array $data = [])`
But as it responds with the status code 204, shouldn't it's signature be `public function respondNoContent()`, so it does not return any content as indicated by the status?

**Comment by ultrono** [comment]
Hi,

Yep, that's basically something to resolve my own issues within a legacy project. As you correctly say, a `204` status code shouldn't return anything. I did semi document this at https://github.com/f9webltd/laravel-api-response-helpers#respondnocontentarray-data--.

Returning data is optional and if you call `$this->respondNoContent()` a `204` will be set as expected.

It may be wiser to change the signature on the readme, what do you think?

Cheers

**Comment by berbeflo** [comment]
I don't know. I think, a clean way would be to make this change in an upcoming version, e.g. 2.0 so the legacy project can require all versions below 2.0
And if there is a need to upgrade the dependency to 2.0 there should be time to refactor the occurrences.

**Comment by ultrono** [comment]
Fair play, for the moment it's fine. The only issue is the semi misleading read me that has been documented. `$this->respondNoContent()` can still be used as normal.
