### ISSUE TITLE
Allow JsonSerializable in addition to array for $contents?

### ISSUE THREAD

**Issue by AdamGaskins** [f9webltd/laravel-api-response-helpers#9]
Love this helper!

Currently this is how I am responding with a JsonResource:

```php
$this->respondWithSuccess(TagResource::collection($tags)->jsonSerialize());
```

It would be cool to be able to also do this!

```php
$this->respondWithSuccess(TagResource::collection($tags));
```

Is that something you would be open to?

**Comment by ultrono** [comment]
Great suggestion, I'm :100:  percent open that that. Will take a proper look at your PR later.

Thanks for contribution!
